"""Student personalization helpers independent from the chat main chain."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from sqlalchemy.orm import Session
    from app.models.personalization import StudentConceptMastery, StudentRiskSignal


SIGNAL_WEIGHTS = {
    "task_score": 0.25,
    "flashcard_success": 0.18,
    "teacher_verified": 0.14,
    "material_view": 0.06,
    "low_confidence": -0.16,
    "dislike": -0.14,
    "repeated_question": -0.10,
}


@dataclass(frozen=True)
class MasteryEvidence:
    concept_name: str
    signal_type: str
    value: float = 1.0
    occurred_at: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


def estimate_mastery_from_evidence(
    evidence_items: list[MasteryEvidence],
    *,
    base_score: float = 0.5,
) -> dict[str, dict[str, Any]]:
    grouped: dict[str, list[MasteryEvidence]] = {}
    for item in evidence_items:
        concept_name = item.concept_name.strip()
        if not concept_name:
            continue
        grouped.setdefault(concept_name, []).append(item)

    results: dict[str, dict[str, Any]] = {}
    for concept_name, rows in grouped.items():
        score = base_score
        breakdown: dict[str, float] = {}
        last_event_at = None
        for row in rows:
            weight = SIGNAL_WEIGHTS.get(row.signal_type, 0.0)
            contribution = weight * _clamp01(row.value)
            score += contribution
            breakdown[row.signal_type] = round(breakdown.get(row.signal_type, 0.0) + contribution, 4)
            if row.occurred_at and (last_event_at is None or row.occurred_at > last_event_at):
                last_event_at = row.occurred_at
        evidence_count = len(rows)
        confidence = min(1.0, 0.2 + evidence_count * 0.12)
        results[concept_name] = {
            "concept_name": concept_name,
            "mastery_score": round(_clamp01(score), 4),
            "confidence": round(confidence, 4),
            "evidence_count": evidence_count,
            "last_event_at": last_event_at,
            "source_breakdown": breakdown,
        }
    return results


def build_risk_signals_from_mastery(
    mastery_rows: list[dict[str, Any]],
    *,
    low_threshold: float = 0.35,
) -> list[dict[str, Any]]:
    risks = []
    for row in mastery_rows:
        mastery_score = float(row.get("mastery_score") or 0.0)
        confidence = float(row.get("confidence") or 0.0)
        if mastery_score > low_threshold or confidence < 0.25:
            continue
        risks.append({
            "risk_type": "low_concept_mastery",
            "risk_level": "high" if mastery_score < 0.2 else "medium",
            "reason": f"Low mastery for {row.get('concept_name')}",
            "evidence": {
                "concept_name": row.get("concept_name"),
                "mastery_score": mastery_score,
                "confidence": confidence,
                "source_breakdown": row.get("source_breakdown") or {},
            },
        })
    return risks


def upsert_mastery_snapshots(
    db: "Session",
    *,
    user_id: str,
    class_id: str,
    mastery_rows: dict[str, dict[str, Any]],
) -> list[StudentConceptMastery]:
    """Persist concept mastery rows generated by estimate_mastery_from_evidence."""

    from app.models.personalization import StudentConceptMastery

    persisted = []
    for concept_name, payload in mastery_rows.items():
        clean_name = str(concept_name or payload.get("concept_name") or "").strip()
        if not clean_name:
            continue
        row = (
            db.query(StudentConceptMastery)
            .filter(
                StudentConceptMastery.user_id == user_id,
                StudentConceptMastery.class_id == class_id,
                StudentConceptMastery.concept_name == clean_name,
            )
            .first()
        )
        if not row:
            row = StudentConceptMastery(
                user_id=user_id,
                class_id=class_id,
                concept_name=clean_name,
            )
            db.add(row)

        row.concept_id = payload.get("concept_id")
        row.mastery_score = float(payload.get("mastery_score", row.mastery_score or 0.5))
        row.confidence = float(payload.get("confidence", row.confidence or 0.0))
        row.evidence_count = int(payload.get("evidence_count", row.evidence_count or 0))
        row.last_event_at = payload.get("last_event_at")
        row.source_breakdown = payload.get("source_breakdown") or {}
        row.extra_data = payload.get("extra_data") or {}
        persisted.append(row)

    db.flush()
    return persisted


def persist_risk_signals(
    db: "Session",
    *,
    user_id: str,
    class_id: str,
    risk_rows: list[dict[str, Any]],
) -> list[StudentRiskSignal]:
    """Persist open risk signals without closing older signals automatically."""

    from app.models.personalization import StudentRiskSignal

    persisted = []
    for payload in risk_rows:
        risk_type = str(payload.get("risk_type") or "").strip()
        if not risk_type:
            continue
        row = StudentRiskSignal(
            user_id=user_id,
            class_id=class_id,
            risk_type=risk_type,
            risk_level=str(payload.get("risk_level") or "low"),
            reason=payload.get("reason"),
            evidence=payload.get("evidence") or {},
            status=str(payload.get("status") or "open"),
        )
        db.add(row)
        persisted.append(row)

    db.flush()
    return persisted


def update_mastery_from_evidence(
    db: "Session",
    *,
    user_id: str,
    class_id: str,
    evidence_items: list[MasteryEvidence],
) -> dict[str, Any]:
    """Compute and persist mastery plus risk signals in one transaction scope."""

    mastery = estimate_mastery_from_evidence(evidence_items)
    mastery_rows = upsert_mastery_snapshots(
        db,
        user_id=user_id,
        class_id=class_id,
        mastery_rows=mastery,
    )
    risk_payloads = build_risk_signals_from_mastery(list(mastery.values()))
    risks = persist_risk_signals(
        db,
        user_id=user_id,
        class_id=class_id,
        risk_rows=risk_payloads,
    )
    return {
        "mastery_count": len(mastery_rows),
        "risk_count": len(risks),
        "mastery": mastery,
        "risks": risk_payloads,
    }


def _clamp01(value: float | int | None) -> float:
    try:
        numeric = float(value if value is not None else 0.0)
    except (TypeError, ValueError):
        numeric = 0.0
    return max(0.0, min(1.0, numeric))
